In [ ]:
import numpy as np

In [ ]:
array1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(array1)
print(type(array1))
print(array1.shape)


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [ ]:
odd = slice(1,10,2)
print('Odd array:')
print(array1[odd])
even = slice(0,10,2)
print('Event array:')
print(array1[even])

Odd array:
[1 3 5 7 9]
Event array:
[0 2 4 6 8]


In [ ]:
array_update = array1[array1==2]
print(array_update)