In [9]:
import numpy as np
from fractions import Fraction

In [6]:
n = 3

arrGear = np.eye(n)
arrGear += np.roll(arrGear, 1)
print("arrGrear pre mod:\n", arrGear)

# Khi shift thì ma trận được flat -> convert ngược 
# nên phải chỉnh tay hàng đầu, cuối

arrGear[0][0] = 1
arrGear[n - 1][0] = 1
arrGear[n - 1][n - 1] = -2
print(arrGear)


arrGrear pre mod:
 [[2. 1. 0.]
 [0. 1. 1.]
 [0. 0. 1.]]
[[ 1.  1.  0.]
 [ 0.  1.  1.]
 [ 1.  0. -2.]]


In [3]:
pegs = [4, 30, 50]
arrGearEx = [(pegs[i+1] - pegs[i]) for i in range(len(pegs)-1)]
arrGearEx[-1] = 0
print(arrGearEx)

[26, 0]


In [16]:
# demo numpy linear algebra determinant of a matrix
arrA = np.array([[2,1,0],[1,0,3],[0,5,-1]])
detA = round(np.linalg.det(arrA))
print('detA: ', detA)
detArrA = Fraction(detA)
print('detArrA: ', detArrA)
print('col2: ',arrA[:,2])

detA:  -29
detArrA:  -29
col2:  [ 0  3 -1]


In [17]:
arrResult = []
arrA_ext = [5, 16, 10]
for i in range(3):
    arrA_ext_temp = np.copy(arrA)
    arrA_ext_temp[:, i] = arrA_ext
    arrResult.append(Fraction(round(np.linalg.det(arrA_ext_temp))) / detArrA)
print(arrResult)

[Fraction(1, 1), Fraction(3, 1), Fraction(5, 1)]
