In [1]:
import numpy as np

In [2]:
weights = np.array([67.0, 45.0, 65.9, 45.3, 46.0, 67.8])

In [3]:
weights

array([67. , 45. , 65.9, 45.3, 46. , 67.8])

In [4]:
weights.size

6

In [5]:
weights.shape

(6,)

In [6]:
type(weights)

numpy.ndarray

In [10]:
a = np.arange(10,30,2)

In [11]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
a = np.array([[3,4,7,2],[5,8,1,0],[3,2,7,3]])

In [15]:
a

array([[3, 4, 7, 2],
       [5, 8, 1, 0],
       [3, 2, 7, 3]])

In [16]:
a.shape

(3, 4)

In [17]:
a.size

12

In [18]:
a = np.array([3,4,7,2,2,7,3])

In [19]:
a

array([3, 4, 7, 2, 2, 7, 3])

In [20]:
a[1]=9

In [21]:
a

array([3, 9, 7, 2, 2, 7, 3])

In [22]:
a[-1]=7

In [23]:
a

array([3, 9, 7, 2, 2, 7, 7])

In [24]:
a[-2]=15

In [25]:
a

array([ 3,  9,  7,  2,  2, 15,  7])

In [26]:
a = np.arange(1,30,2)

In [27]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [29]:
b = a[a<20]

In [30]:
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [32]:
cond = a<20
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False])

In [33]:
a[cond]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
a = np.arange(1,10,2)

In [35]:
a

array([1, 3, 5, 7, 9])

In [37]:
b = a+5

In [38]:
b

array([ 6,  8, 10, 12, 14])

In [42]:
weights = np.array([67.0, 45.0, 65.9, 45.3, 46.0, 67.8])

In [43]:
np.min(weights)

45.0

In [44]:
np.max(weights)

67.8

In [45]:
np.mean(weights)

56.166666666666664

In [46]:
np.sum(weights)

337.0

In [47]:
weights.sum()

337.0

In [48]:
weights.max()

67.8

In [49]:
# trung binh (mean)
weights.mean()

56.166666666666664

In [51]:
# trung vi (median)
np.median(weights)

55.95

In [52]:
weights

array([67. , 45. , 65.9, 45.3, 46. , 67.8])

In [53]:
print(weights)

[67.  45.  65.9 45.3 46.  67.8]


In [54]:
np.sort(weights) # sap tang

array([45. , 45.3, 46. , 65.9, 67. , 67.8])

In [55]:
np.sort(weights)[::-1] # sap giam

array([67.8, 67. , 65.9, 46. , 45.3, 45. ])

In [56]:
weights[0]

67.0

In [57]:
weights[2:]

array([65.9, 45.3, 46. , 67.8])

In [58]:
weights[0:5]

array([67. , 45. , 65.9, 45.3, 46. ])

In [59]:
weights[[0,2,4]]

array([67. , 65.9, 46. ])

In [67]:
a = np.arange(30)

In [68]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [69]:
np.extract(np.mod(a,2)==0,a)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [71]:
np.extract((np.mod(a,2)==0) & (a>=20), a) # & and, | or, ~ not

array([20, 22, 24, 26, 28])