In [1]:
import numpy as np

In [2]:
# mang 2 chieu: so dong va so cot
a = np.array([[2,5],[3,6],[7,2]])

In [3]:
a

array([[2, 5],
       [3, 6],
       [7, 2]])

In [4]:
a.shape

(3, 2)

In [5]:
a[0,1]

5

In [6]:
a[2,0]

7

In [7]:
a[0]

array([2, 5])

In [8]:
a

array([[2, 5],
       [3, 6],
       [7, 2]])

In [9]:
a[:,0]

array([2, 3, 7])

In [10]:
a[1:,:]

array([[3, 6],
       [7, 2]])

In [12]:
# mang 3 chieu: so ma tran, so dong va so cot
a = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [13]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
a.shape

(2, 2, 3)

In [15]:
a[0,1,1]

5

In [16]:
a[1,0,2]

9

In [17]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
b = a[1]

In [19]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [20]:
a = np.arange(24)

In [21]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
a.shape = (12,2)

In [26]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [27]:
a.shape = (3,2,4)

In [28]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
a = np.array([[6.5,8.9,7.8,7.0], [4.5,6.5,6.0,4.0], [5.0,9.0,10.0,8.9]])

In [30]:
a

array([[ 6.5,  8.9,  7.8,  7. ],
       [ 4.5,  6.5,  6. ,  4. ],
       [ 5. ,  9. , 10. ,  8.9]])

In [31]:
# tim diem lon nhat cua tat ca cac mon
np.max(a)

10.0

In [32]:
# tim diem nho nhat cua tat ca cac mon
np.min(a)

4.0

In [33]:
# tim diem nho nhat cua mon van (cot 0)
np.min(a,0)

array([4.5, 6.5, 6. , 4. ])

In [34]:
np.min(a,0)[0]

4.5

In [35]:
a

array([[ 6.5,  8.9,  7.8,  7. ],
       [ 4.5,  6.5,  6. ,  4. ],
       [ 5. ,  9. , 10. ,  8.9]])

In [36]:
# tinh diem trung binh cho moi hoc sinh
np.mean(a,1)

array([7.55 , 5.25 , 8.225])

In [39]:
np.mean(a[2])

8.225

In [44]:
a = np.arange(1,31).reshape((6,5))

In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])